### ISSUE TITLE
Meta.pm contains incorrect information

### ISSUE THREAD

**Issue by compeak** [plenigo/plenigo_perl_sdk#5]
There are several incorrect or incomplete pieces of information in `Meta.pm`:

- [The module name in the NAME section of the POD is incorrect.](https://github.com/plenigo/plenigo_perl_sdk/blob/master/lib/Meta.pm#L7)
- [The description is missing.](https://github.com/plenigo/plenigo_perl_sdk/blob/master/lib/Meta.pm#L11)
- [The author is incorrect.](https://github.com/plenigo/plenigo_perl_sdk/blob/master/lib/Meta.pm#L15)
- The [license](https://github.com/plenigo/plenigo_perl_sdk/blob/master/GNU-AGPL-3.0.txt) contradicts the [license file](https://github.com/plenigo/plenigo_perl_sdk/blob/master/GNU-AGPL-3.0.txt).

**Comment by maximilianschweitzer** [comment]
Thank you very much for the feedback. Should be fixed now and a new version was released.

**Comment by compeak** [comment]
Thanks.
